20221013pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('',views.user_list, name='user_list'),
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/', views.detail, name='detail'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('<int:pk>/update/', views.update, name='update'),
    #비밀번호 변경
    path('password/', views.change_password, name='change_password'),
    #탈퇴
    path('delete/', views.delete, name="delete"),
    #회원 검색
    path('search/', views.search, name='search'),
]

20221013pjt/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

# 회원가입
class CustomUserCreationFrom(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'password1',
            'password2',
        ]

# 회원 수정
class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'email',
        ]

20221013pjt/accounts/views.py
import re
from django.shortcuts import render, redirect
from .forms import CustomUserCreationFrom, CustomUserChangeForm
from .models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.db.models import Q
# Create your views here.

# 메인화면

def index(request):
    
    return render(request, 'base.html')

# 회원가입
def signup(request):

    if request.method == 'POST':
        user_form = CustomUserCreationFrom(request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect('/')

    else:
        user_form = CustomUserCreationFrom()

    context = {
        'user_form': user_form,
    }
    return render(request, 'accounts/signup.html', context)

# 전체 회원 조회
@login_required

def user_list(request):
    users = User.objects.all()
    context = {
        'users': users,
    }
    return render(request,'accounts/user_list.html',context)

@login_required
# 회원 상세 조회

def detail(request, pk):

    user = User.objects.get(pk=pk)
    context = {
        'user':user,
    }
    return render(request, 'accounts/detail.html', context)

# 로그인

def user_login(request):
    
    if request.method == 'POST':
        login_form = AuthenticationForm(request,data=request.POST)
        if login_form.is_valid():
            login(request, login_form.get_user())           
            return redirect('/')
    else:
        login_form = AuthenticationForm()

    context = {
        'login_form':login_form,
    }
    return render(request,'accounts/login.html',context)

# 로그아웃
def user_logout(request):
    
    logout(request)
    return redirect('/')

@login_required
# 회원정보 수정
def update(request, pk):
    if request.method == 'POST':
        user_form = CustomUserChangeForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            return redirect('accounts:detail', request.user.pk)
    
    else:
        user_form = CustomUserChangeForm(instance=request.user)
    
    context = {
        'user_form':user_form,
    }
    return render(request,'accounts/update.html', context)

# 비밀번호 변경

@login_required
def change_password(request):
    if request.method == 'POST':
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            password_form.save()
            # 비밀번호 병경후 자동 로그인(세션 업데이트를 자동으로 해줌)
            # login(request, user)를 할 경우 비밀번호 변경전 세션으로 새로변경한 비밀번호의 세션과 충돌
            update_session_auth_hash(request, password_form.user)
            return redirect('accounts:detail', request.user.pk)
    else:
        password_form = PasswordChangeForm(request.user)

    context = {
        'password_form': password_form,
    }
    return render(request,'accounts/change_password.html', context)

#탈퇴
@login_required
def delete(request):
    # 탈퇴후 > 로그아웃 해야한다
    request.user.delete()
    logout(request)

    return redirect('/')

#회원검색
@login_required
def search(request):

    if 'kw' in request.GET:
        query = request.GET.get('kw')
        users = User.objects.all().filter(
            Q(username__icontains = query)
        )
    context = {
        'query': query,
        'users': users,
    }

    return render(request, 'accounts/search.html', context)

20221013pjt/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <form action="" , method="POST">
        {% csrf_token %}
        {% bootstrap_form password_form %}
        {% bootstrap_button button_type="submit" content="비밀번호 변경" %}
    </form>

</div>

{% endblock%}

20221013pjt/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
<div class="container">
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">pk</th>
                <th scope="col">아이디</th>
                <th scope="col">이름</th>
                <th scope="col">이메일</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ user.pk }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.last_name }}{{ user.first_name }}</td>
                <td>{{ user.email }}</td>
            </tr>
        </tbody>
    </table>
    <div class="control_hidden">
        <div class="d-flex flex-row-reverse">
            <div class="mx-1">
                <a href="{% url 'accounts:delete' %}" onclick="return confirm('정말 탈퇴하시겠습니까?')">
                    {% bootstrap_button button_type="submit" content="탈퇴" %}
                </a>
            </div>
            <div class="mx-1">
                <a href="{% url 'accounts:change_password'%}">
                    {% bootstrap_button button_type="submit" content="비밀번호 변경" %}
                </a>
            </div>
            <div div class="mx-1">
                <a href="{% url 'accounts:update' user.pk %}">
                    {% bootstrap_button button_type="submit" content="정보수정" %}
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock%}

20221013pjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <form action="" , method="POST">
        {% csrf_token %}
        {% bootstrap_form login_form %}
        {% bootstrap_button button_type="submit" content="로그인" %}
    </form>

</div>

{% endblock%}

20221013pjt/accounts/templates/accounts/search.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
<div class="container">
    <div>
        <h3>"{{ query }}" 에 대한 검색결과</h3>
    </div>

    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">pk</th>
                <th scope="col">아이디</th>
                <th scope="col">이름</th>
                <th scope="col">이메일</th>
            </tr>
        </thead>
        {% if users %}
        {% if query == "" %}
        <h4>검색어를 입력해주세요.</h4>
        {% else %}
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.pk }}</td>
                {% if user.username == request.user.username %}
                <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
                {% else %}
                <td>{{ user.username }}</td>
                {% endif %}
                <td>{{ user.last_name }}{{ user.first_name }}</td>
                <td>{{ user.email }}</td>
            </tr>
        </tbody>
        {% endfor %}
        {% endif %}
        {% else %}
        <h4>검색결과가 없습니다.</h4>

        {% endif %}
    </table>

    {% endblock%}

20221013pjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <form action="" , method="POST">
        {% csrf_token %}
        {% bootstrap_form user_form %}
        {% bootstrap_button button_type="submit" content="회원가입" %}
    </form>

</div>

{% endblock%}

20221013pjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <form action="" , method="POST">
        {% csrf_token %}
        {% bootstrap_form user_form %}
        {% bootstrap_button button_type="submit" content="수정" %}
    </form>

</div>

{% endblock%}

20221013pjt/accounts/templates/accounts/user_list.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<table class="table text-center">
    <thead>
        <tr>
            <th scope="col">pk</th>
            <th scope="col">아이디</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.pk }}</td>
            {% if user.username == request.user.username %}
            <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
            {% else %}
            <td>{{ user.username }}</td>
            {% endif%}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock%}