20221014pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("index/", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("password_change/", views.password_change, name="password_change"),
    path("delete/", views.delete, name="delete"),
    path("search/", views.search, name="search"),
]

20221014pjt/accounts/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

20221014pjt/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'password1',
            'password2',
        ]

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'email',
        ]

20221014pjt/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as user_login
from django.contrib.auth import logout as user_logout
from django.contrib.auth import update_session_auth_hash, authenticate
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.

# 홈페이지


def main(request):

    return render(request, "base.html")


# 회원가입


def signup(request):

    if request.method == "POST":
        user_form = CustomUserCreationForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            username = user_form.cleaned_data.get("username")
            direct_password = user_form.cleaned_data.get("password1")
            user = authenticate(username=username, password=direct_password)
            user_login(request, user)
            return redirect("/")

    else:
        user_form = CustomUserCreationForm()

    context = {
        "user_form": user_form,
    }
    return render(request, "accounts/signup.html", context)


# 로그인


def login(request):

    if request.method == "POST":
        login_form = AuthenticationForm(request, data=request.POST)
        if login_form.is_valid():
            user_login(request, login_form.get_user())
            return redirect("/")

    else:
        login_form = AuthenticationForm()

    context = {
        "login_form": login_form,
    }
    return render(request, "accounts/login.html", context)


# 로그아웃


@login_required
def logout(request):

    user_logout(request)

    return redirect("/")


# 회원 목록 조회


@login_required
def index(request):

    users = User.objects.all()
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)


# 회원 프로필 조회


@login_required
def detail(request, pk):

    user = User.objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


# 회원정보 수정


@login_required
def update(request):

    if request.method == "POST":
        update_form = CustomUserChangeForm(request.POST, instance=request.user)
        if update_form.is_valid():
            update_form.save()

            return redirect("accounts:detail", request.user.pk)

    else:
        update_form = CustomUserChangeForm(instance=request.user)

    context = {
        "update_form": update_form,
    }

    return render(request, "accounts/update.html", context)


# 비밀번호 변경


@login_required
def password_change(request):

    if request.method == "POST":
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            password_form.save()
            update_session_auth_hash(request, request.user)

            return redirect("accounts:detail", request.user.pk)

    else:
        password_form = PasswordChangeForm(request.user)

    context = {
        "password_form": password_form,
    }

    return render(request, "accounts/password_change.html", context)


# 회원 탈퇴


@login_required
def delete(request):

    request.user.delete()
    user_logout(request)

    return redirect("/")


# 검색


@login_required
def search(request):

    if "검색어" in request.GET:
        query = request.GET.get("검색어")

        users = User.objects.all().filter(Q(username__icontains=query))

        context = {
            "query": query,
            "users": users,
        }

        return render(request, "accounts/search.html", context)

20221014pjt/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">pk</th>
                <th scope="col">아이디</th>
                <th scope="col">이름</th>
                <th scope="col">이메일</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ user.pk }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.last_name }}{{ user.first_name }}</td>
                <td>{{ user.email }}</td>
            </tr>

        </tbody>
    </table>
    <div class="d-flex d-flex justify-content-end">
        <div class="row gx-1">
            <div class="col">
                <a href="{% url 'accounts:update'%}">
                    <div class="" style="width: 7rem;">
                        {% bootstrap_button button_type="submit" content="프로필 수정" %}
                    </div>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'accounts:password_change' %}">
                    <div class="" style="width: 8rem;">
                        {% bootstrap_button button_type="submit" content="비밀번호 변경" %}
                    </div>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'accounts:delete' %}" onclick="return confirm('정말 탈퇴하시겠습니까?')">
                    <div class="">
                        {% bootstrap_button button_type="submit" content="탈퇴" %}
                    </div>
                </a>

            </div>
        </div>


    </div>
</div>



{% endblock %}

20221014pjt/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">pk</th>
                <th scope="col">아이디</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.pk }}</td>
                {% if user.username == request.user.username %}
                <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
                {% else %}
                <td>{{ user.username }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex flex-start-end">
        <form action="{% url 'accounts:search' %}" class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="아이디를 입력하세요" aria-label="Search" name="검색어">
            <button class="btn btn-primary" type="submit" style="width: 6rem;">검색</button>
        </form>
    </div>

</div>



{% endblock %}

20221014pjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <form action="" method='POST'>
        {% csrf_token %}
        {% bootstrap_form login_form%}
        {% bootstrap_button button_type="submit" content="로그인" %}
    </form>

</div>



{% endblock %}

20221014pjt/accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <form action="" method='POST'>
        {% csrf_token %}
        {% bootstrap_form password_form %}
        {% bootstrap_button button_type="submit" content="변경" %}
    </form>

</div>



{% endblock %}

20221014pjt/accounts/templates/accounts/search.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">pk</th>
                <th scope="col">아이디</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.pk }}</td>
                {% if user.username == request.user.username %}
                <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
                {% else %}
                <td>{{ user.username }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex flex-start-end">
        <form action="{% url 'accounts:search' %}" class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="아이디를 입력하세요" aria-label="Search" name="검색어">
            <button class="btn btn-primary" type="submit" style="width: 6rem;">검색</button>
        </form>
    </div>

</div>



{% endblock %}

20221014pjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <form action="" method='POST'>
        {% csrf_token %}
        {% bootstrap_form user_form%}
        {% bootstrap_button button_type="submit" content="회원가입" %}
    </form>

</div>



{% endblock %}

20221014pjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}

<div class="container">
    <form action="" method='POST'>
        {% csrf_token %}
        {% bootstrap_form update_form%}
        {% bootstrap_button button_type="submit" content="수정" %}
    </form>

</div>



{% endblock %}