20221013pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('',views.user_list, name='user_list'),
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/', views.detail, name='detail'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('<int:pk>/update/', views.update, name='update'),
    #비밀번호 변경
    path('password/', views.change_password, name='change_password'),
    #탈퇴
    path('delete/', views.delete, name="delete"),
    #회원 검색
    path('search/', views.search, name='search'),
]

20221013pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

20221013pjt/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

# 회원가입
class CustomUserCreationFrom(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'password1',
            'password2',
        ]

# 회원 수정
class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'email',
        ]

20221013pjt/accounts/views.py
import re
from django.shortcuts import render, redirect
from .forms import CustomUserCreationFrom, CustomUserChangeForm
from .models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.db.models import Q
# Create your views here.

# 메인화면

def index(request):
    
    return render(request, 'base.html')

# 회원가입
def signup(request):

    if request.method == 'POST':
        user_form = CustomUserCreationFrom(request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect('/')

    else:
        user_form = CustomUserCreationFrom()

    context = {
        'user_form': user_form,
    }
    return render(request, 'accounts/signup.html', context)

# 전체 회원 조회
@login_required

def user_list(request):
    users = User.objects.all()
    context = {
        'users': users,
    }
    return render(request,'accounts/user_list.html',context)

@login_required
# 회원 상세 조회

def detail(request, pk):

    user = User.objects.get(pk=pk)
    context = {
        'user':user,
    }
    return render(request, 'accounts/detail.html', context)

# 로그인

def user_login(request):
    
    if request.method == 'POST':
        login_form = AuthenticationForm(request,data=request.POST)
        if login_form.is_valid():
            login(request, login_form.get_user())           
            return redirect('/')
    else:
        login_form = AuthenticationForm()

    context = {
        'login_form':login_form,
    }
    return render(request,'accounts/login.html',context)

# 로그아웃
def user_logout(request):
    
    logout(request)
    return redirect('/')

@login_required
# 회원정보 수정
def update(request, pk):
    if request.method == 'POST':
        user_form = CustomUserChangeForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            return redirect('accounts:detail', request.user.pk)
    
    else:
        user_form = CustomUserChangeForm(instance=request.user)
    
    context = {
        'user_form':user_form,
    }
    return render(request,'accounts/update.html', context)

# 비밀번호 변경

@login_required
def change_password(request):
    if request.method == 'POST':
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            password_form.save()
            # 비밀번호 병경후 자동 로그인(세션 업데이트를 자동으로 해줌)
            # login(request, user)를 할 경우 비밀번호 변경전 세션으로 새로변경한 비밀번호의 세션과 충돌
            update_session_auth_hash(request, password_form.user)
            return redirect('accounts:detail', request.user.pk)
    else:
        password_form = PasswordChangeForm(request.user)

    context = {
        'password_form': password_form,
    }
    return render(request,'accounts/change_password.html', context)

#탈퇴
@login_required
def delete(request):
    # 탈퇴후 > 로그아웃 해야한다
    request.user.delete()
    logout(request)

    return redirect('/')

#회원검색
@login_required
def search(request):

    if 'kw' in request.GET:
        query = request.GET.get('kw')
        users = User.objects.all().filter(
            Q(username__icontains = query)
        )
    context = {
        'query': query,
        'users': users,
    }

    return render(request, 'accounts/search.html', context)

20221013pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        a {
            text-decoration: none;
        }
    </style>

</head>

<body>
    <nav class="navbar bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">사이트</a>
            <div class="menu d-flex flex-row-reverse">
                {% if request.user.is_authenticated %}

                <div class="d-flex align-items-center logoutbtn mx-2">
                    {% if not request.user.last_name and not request.user.first_name %}
                    <a href="{% url 'accounts:detail' request.user.pk %}">
                        Anonymous 님
                    </a>
                    {% else %}
                    <a href="{% url 'accounts:detail' request.user.pk %}">
                        {{ request.user.last_name }}{{request.user.first_name }} 님
                    </a>
                    {% endif %}
                </div>
                <div class>
                    <a href="{% url 'accounts:user_list' %}">
                        <button class="btn btn-outline-success" type="submit">회원목록</button>
                    </a>
                </div>
                <div class="mx-1">
                    <a href="{% url 'accounts:user_logout' %}">
                        <button class="btn btn-outline-success" type="submit">로그아웃</button>
                    </a>
                </div>
                <div class="me-2">
                    <form class="d-flex" action="{% url 'accounts:search' %}" role="search">
                        <input class="form-control me-1" type="search" placeholder="아이디 검색" name="kw">
                        <button class="btn btn-outline-success" type="submit" style="width: 8rem;">검색</button>
                    </form>
                </div>
            </div>
            {% else %}
            <div class="mx-2">
                <a href="{% url 'accounts:signup' %}">
                    <button class="btn btn-outline-success" type="submit">회원가입</button>
                </a>
            </div>
            <a href="{% url 'accounts:user_login' %}">
                <button class="btn btn-outline-success" type="submit">로그인</button>
            </a>
            {% endif %}
        </div>
        </div>
    </nav>

    {% block content %}

    {% endblock %}
</body>

</html>