20221014pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("index/", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("password_change/", views.password_change, name="password_change"),
    path("delete/", views.delete, name="delete"),
    path("search/", views.search, name="search"),
]

20221014pjt/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('',views.main),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

20221014pjt/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("create/", views.create, name="create"),
    path("index/", views.index, name="index"),
    path("<int:review_pk>/", views.detail, name="detail"),
    path("<int:review_pk>/update/", views.update, name="update"),
    path("<int:review_pk>/delete/", views.delete, name="delete"),
    path("search/", views.search, name="search"),
    # 댓글
    path("<int:pk>/add_comment/", views.add_comment, name="add_comment"),
    path("<int:pk>/comment_remove/", views.comment_remove, name="comment_remove"),
    path("<int:pk>/comment_modify/", views.comment_modify, name="comment_modify"),
]

20221014pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        a {
            text-decoration: none;
        }
    </style>
</head>

<body>

    <nav class="d-flex navbar navbar-expand-lg bg-light mb-5">

        <div class="container-fluid">
            <a class="navbar-brand" href="/">홈페이지</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if request.user.is_authenticated %}

                    <li class="nav-item">
                        {% if not request.user.last_name or not request.user.first_name %}
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'accounts:detail' request.user.pk %}">
                            Anonymous 님
                        </a>
                        {% else %}
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'accounts:detail' request.user.pk %}">
                            {{ request.user.last_name }}{{ request.user.first_name }} 님
                        </a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">로그아웃</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:index' %}">회원 목록</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'reviews:index' %}">게시글 목록</a>
                    </li>

                </ul>
            </div>

            {% else %}

            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'reviews:index' %}">게시글 목록</a>
            </li>

            {% endif %}

        </div>
        </div>
    </nav>


    {% block content %}

    {% endblock %}
</body>

</html>